<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{block head}
<!-- mobile viewport optimisation -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- stylesheets -->
<link rel="stylesheet" href="/_resource/css/yaml412-130728/yaml/core/base.min.css" type="text/css"/>
<link rel="stylesheet" href="/_resource/css/yaml412-130728/yaml/screen/typography.css" type="text/css"/>
<link rel="stylesheet" href="/_resource/css/yaml412-130728/yaml/forms/gray-theme.css" type="text/css"/>
<!--[if lte IE 7]>
<link rel="stylesheet" href="/_resource/css/yaml412-130728/yaml/core/iehacks.min.css" type="text/css"/>
<![endif]-->
<script src="/_resource/js/jquery-1.8.3.min.js"></script>
{$smarty.block.child}
{/block}
<title>{block title}{/block}</title>
</head>

<body>
{block name="body"}{/block}
</body>
</html>